openapi: 3.1.0
info:
  title: Google Cloud Container Registry Blobs  Catalog API
  description: The Container Registry API provides access to store, manage, and secure Docker container images. It supports pushing and pulling images, managing image tags, and integrating with vulnerability scanning and binary authorization services.
  version: v1
  contact:
    name: Google Cloud
    url: https://cloud.google.com/container-registry
servers:
- url: https://containerregistry.googleapis.com
tags:
- name: ' Catalog'
paths:
  /v2/_catalog:
    get:
      operationId: listCatalog
      summary: Google Cloud Container Registry List Repositories
      description: Lists repositories in the registry.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatalogResponse'
      tags:
      - ' Catalog'
components:
  schemas:
    CatalogResponse:
      type: object
      properties:
        repositories:
          type: array
          items:
            type: string
          description: The list of repository names.
externalDocs:
  description: Google Cloud Container Registry Documentation
  url: https://cloud.google.com/container-registry/docs
